CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  oauth2_provider VARCHAR(100) NOT NULL,
  oauth2_sub VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255),
  email VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);