/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthenticatedRouteImport } from './routes/app/_authenticated'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'

const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/app': typeof AppAuthenticatedRouteWithChildren
  '/app/': typeof AppAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/app': typeof AppAuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oauth-callback' | '/app' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oauth-callback' | '/app'
  id:
    | '__root__'
    | '/'
    | '/oauth-callback'
    | '/app/_authenticated'
    | '/app/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
  }
}

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
