// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateItemData, CreateItemErrors, CreateItemResponses, CreateListData, CreateListErrors, CreateListResponses, DeleteItemData, DeleteItemErrors, DeleteItemResponses, DeleteListData, DeleteListErrors, DeleteListResponses, DeleteUserData, DeleteUserResponses, GetListByIdData, GetListByIdErrors, GetListByIdResponses, GetListsData, GetListsResponses, GetUserData, GetUserResponses, ReorderItemsData, ReorderItemsErrors, ReorderItemsResponses, UpdateItemData, UpdateItemErrors, UpdateItemResponses, UpdateListData, UpdateListErrors, UpdateListResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all lists
 *
 * Retrieves all lists of a specific user
 */
export const getLists = <ThrowOnError extends boolean = false>(options?: Options<GetListsData, ThrowOnError>) => (options?.client ?? client).get<GetListsResponses, unknown, ThrowOnError>({ url: '/api/v1/lists', ...options });

/**
 * Create a new list
 *
 * Add a new list to the system
 */
export const createList = <ThrowOnError extends boolean = false>(options: Options<CreateListData, ThrowOnError>) => (options.client ?? client).post<CreateListResponses, CreateListErrors, ThrowOnError>({
    url: '/api/v1/lists',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a new item
 *
 * Add a new item to the system
 */
export const createItem = <ThrowOnError extends boolean = false>(options: Options<CreateItemData, ThrowOnError>) => (options.client ?? client).post<CreateItemResponses, CreateItemErrors, ThrowOnError>({
    url: '/api/v1/lists/{listId}/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete current user
 *
 * Deletes the authenticated user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options?: Options<DeleteUserData, ThrowOnError>) => (options?.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({ url: '/api/v1/user', ...options });

/**
 * Get current user
 *
 * Retrieve details of the authenticated user
 */
export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) => (options?.client ?? client).get<GetUserResponses, unknown, ThrowOnError>({ url: '/api/v1/user', ...options });

/**
 * Update current user
 *
 * Update details of the authenticated user
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    url: '/api/v1/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an item
 *
 * Delete a specific item from the list
 */
export const deleteItem = <ThrowOnError extends boolean = false>(options: Options<DeleteItemData, ThrowOnError>) => (options.client ?? client).delete<DeleteItemResponses, DeleteItemErrors, ThrowOnError>({ url: '/api/v1/lists/{listId}/items/{id}', ...options });

/**
 * Update an item
 *
 * Update an existing item's details
 */
export const updateItem = <ThrowOnError extends boolean = false>(options: Options<UpdateItemData, ThrowOnError>) => (options.client ?? client).patch<UpdateItemResponses, UpdateItemErrors, ThrowOnError>({
    url: '/api/v1/lists/{listId}/items/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reorder items in a list
 *
 * Reorder all items within the specified list
 */
export const reorderItems = <ThrowOnError extends boolean = false>(options: Options<ReorderItemsData, ThrowOnError>) => (options.client ?? client).patch<ReorderItemsResponses, ReorderItemsErrors, ThrowOnError>({
    url: '/api/v1/lists/{listId}/items/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a list
 *
 * Deletes a list and all its associated items
 */
export const deleteList = <ThrowOnError extends boolean = false>(options: Options<DeleteListData, ThrowOnError>) => (options.client ?? client).delete<DeleteListResponses, DeleteListErrors, ThrowOnError>({ url: '/api/v1/lists/{id}', ...options });

/**
 * Get a list by ID
 *
 * Retrieves details of a specific list
 */
export const getListById = <ThrowOnError extends boolean = false>(options: Options<GetListByIdData, ThrowOnError>) => (options.client ?? client).get<GetListByIdResponses, GetListByIdErrors, ThrowOnError>({ url: '/api/v1/lists/{id}', ...options });

/**
 * Update a list
 *
 * Updates details of an existing list
 */
export const updateList = <ThrowOnError extends boolean = false>(options: Options<UpdateListData, ThrowOnError>) => (options.client ?? client).patch<UpdateListResponses, UpdateListErrors, ThrowOnError>({
    url: '/api/v1/lists/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
