// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type ListCreateDto = {
    title: string;
    description?: string;
};

export type ProblemDetail = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type ItemCreateDto = {
    title: string;
    notes?: string;
    imagePath?: string;
};

export type UserUpdateDto = {
    oauth2Provider?: string;
    name?: string;
    email?: string;
};

export type ItemUpdateDto = {
    title?: string;
    notes?: string;
    imagePath?: string;
};

export type ItemReorderDto = {
    itemOrder?: Array<string>;
};

export type ListUpdateDto = {
    title?: string;
    description?: string;
};

export type ListSummaryDto = {
    id?: string;
    title?: string;
    itemCount?: number;
};

export type UserResponseDto = {
    id?: string;
    name?: string;
    email?: string;
    createdAt?: string;
    updatedAt?: string;
    version?: number;
    lists?: Array<ListSummaryDto>;
};

export type ItemSummaryDto = {
    id?: string;
    title?: string;
    position?: number;
    imagePath?: string;
};

export type ListResponseDto = {
    id?: string;
    title?: string;
    description?: string;
    createdAt?: string;
    updatedAt?: string;
    version?: number;
    owner?: UserSummaryDto;
    items?: Array<ItemSummaryDto>;
};

export type UserSummaryDto = {
    id?: string;
    name?: string;
};

export type GetListsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/lists';
};

export type GetListsResponses = {
    /**
     * Lists retrieved successfully
     */
    200: Array<ListResponseDto>;
};

export type GetListsResponse = GetListsResponses[keyof GetListsResponses];

export type CreateListData = {
    body: ListCreateDto;
    path?: never;
    query?: never;
    url: '/api/v1/lists';
};

export type CreateListErrors = {
    /**
     * Invalid request data
     */
    400: ProblemDetail;
};

export type CreateListError = CreateListErrors[keyof CreateListErrors];

export type CreateListResponses = {
    /**
     * List created successfully
     */
    201: string;
};

export type CreateListResponse = CreateListResponses[keyof CreateListResponses];

export type CreateItemData = {
    body: ItemCreateDto;
    path: {
        /**
         * ID of the list to add the item to
         */
        listId: string;
    };
    query?: never;
    url: '/api/v1/lists/{listId}/items';
};

export type CreateItemErrors = {
    /**
     * Invalid request data
     */
    400: ProblemDetail;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
    /**
     * Item created successfully
     */
    201: string;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type DeleteUserResponses = {
    /**
     * User account deleted successfully
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type GetUserResponses = {
    /**
     * User retrieved successfully
     */
    200: UserResponseDto;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserUpdateDto;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type UpdateUserErrors = {
    /**
     * Invalid request data
     */
    400: ProblemDetail;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * User updated successfully
     */
    200: string;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DeleteItemData = {
    body?: never;
    path: {
        /**
         * ID of the list containing the item
         */
        listId: string;
        /**
         * ID of the item to delete
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lists/{listId}/items/{id}';
};

export type DeleteItemErrors = {
    /**
     * Forbidden (insufficient permissions)
     */
    403: unknown;
    /**
     * List or item not found
     */
    404: unknown;
};

export type DeleteItemResponses = {
    /**
     * Item deleted successfully
     */
    204: void;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type UpdateItemData = {
    body: ItemUpdateDto;
    path: {
        /**
         * ID of the list containing the item
         */
        listId: string;
        /**
         * ID of the item to update
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lists/{listId}/items/{id}';
};

export type UpdateItemErrors = {
    /**
     * Invalid request data
     */
    400: ProblemDetail;
    /**
     * Forbidden
     */
    403: string;
    /**
     * List or item not found
     */
    404: string;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
    /**
     * Item updated successfully
     */
    200: string;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];

export type ReorderItemsData = {
    body: ItemReorderDto;
    path: {
        /**
         * ID of the list to reorder items in
         */
        listId: string;
    };
    query?: never;
    url: '/api/v1/lists/{listId}/items/order';
};

export type ReorderItemsErrors = {
    /**
     * Invalid reorder data
     */
    400: ProblemDetail;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * List not found
     */
    404: unknown;
};

export type ReorderItemsError = ReorderItemsErrors[keyof ReorderItemsErrors];

export type ReorderItemsResponses = {
    /**
     * Items reordered successfully
     */
    204: void;
};

export type ReorderItemsResponse = ReorderItemsResponses[keyof ReorderItemsResponses];

export type DeleteListData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lists/{id}';
};

export type DeleteListErrors = {
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * List not found
     */
    404: unknown;
};

export type DeleteListResponses = {
    /**
     * List deleted successfully
     */
    204: void;
};

export type DeleteListResponse = DeleteListResponses[keyof DeleteListResponses];

export type GetListByIdData = {
    body?: never;
    path: {
        /**
         * ID of the list to retrieve
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lists/{id}';
};

export type GetListByIdErrors = {
    /**
     * Forbidden
     */
    403: ListResponseDto;
    /**
     * List not found
     */
    404: ListResponseDto;
};

export type GetListByIdError = GetListByIdErrors[keyof GetListByIdErrors];

export type GetListByIdResponses = {
    /**
     * List retrieved successfully
     */
    200: ListResponseDto;
};

export type GetListByIdResponse = GetListByIdResponses[keyof GetListByIdResponses];

export type UpdateListData = {
    body: ListUpdateDto;
    path: {
        /**
         * ID of the list to update
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/lists/{id}';
};

export type UpdateListErrors = {
    /**
     * Invalid request data
     */
    400: ProblemDetail;
    /**
     * Forbidden
     */
    403: string;
    /**
     * List not found
     */
    404: string;
};

export type UpdateListError = UpdateListErrors[keyof UpdateListErrors];

export type UpdateListResponses = {
    /**
     * List updated successfully
     */
    200: string;
};

export type UpdateListResponse = UpdateListResponses[keyof UpdateListResponses];
